fixing examples and using --default-overrides flag

diff --git a/examples/Makefile b/examples/Makefile
--- a/examples/Makefile
+++ b/examples/Makefile
@@ -11,48 +11,52 @@ else
 LEKTOR_BUILD_INPUTS="libffi openssl unzip"
 endif
 
+
 .PHONY: \
+	aiohttp \
 	awscli_and_requests \
+	connexion \
 	empy \
+	flake8 \
 	ldap \
 	lektor \
 	mercurial \
+	pillow \
 	rss2email \
 	scipy \
-	pillow \
 	tornado \
-	vulnix \
-	connexion \
-	aiohttp
+	vulnix
 
 all: \
+	aiohttp \
 	awscli_and_requests \
+	connexion \
 	empy \
+	flake8 \
 	ldap \
 	lektor \
 	mercurial \
+	pillow \
 	rss2email \
 	scipy \
-	pillow \
 	tornado \
-	vulnix \
-	connexion \
-	aiohttp
+	vulnix
 
 clear: \
+	aiohttp-clear \
 	awscli_and_requests-clear \
+	connexion-clear \
 	empy-clear \
+	flake8-clear \
 	ldap-clear \
 	lektor-clear \
 	mercurial-clear \
+	pillow-clear \
 	pypi2nix-clear \
 	rss2email-clear \
 	scipy-clear \
-	pillow-clear \
 	tornado-clear \
-	vulnix-clear \
-	connexion-clear \
-	aiohttp-clear
+	vulnix-clear
 
 
 pypi2nix-clear:
@@ -62,30 +66,100 @@ $(PYPI2NIX): pypi2nix-clear
 	echo "building pypi2nix ..."
 	$(NIX_BUILD) ../release.nix -A build.x86_64-linux -o pypi2nix
 
-pillow: pillow.nix
-	echo "building and testing pillow..."
-	$(NIX_BUILD) pillow.nix -o pillow -A interpreter --show-trace
-	./pillow/bin/python -c 'import PIL'
-	$(NIX_SHELL) pillow.nix -A interpreter --run "python -c 'import PIL'" 
 
-pillow.nix: pillow.txt $(PYPI2NIX)
-	echo "generating pillownix expressions ..."
-	$(PYPI2NIX) \
-		-v \
+
+#------------------------------------------------------------------------------
+
+
+aiohttp: aiohttp.nix
+	echo "building and testing aiohttp..."
+	$(NIX_BUILD) aiohttp.nix -o aiohttp -A interpreter --show-trace -j 1
+	./aiohttp/bin/python -c 'import aiohttp'
+	$(NIX_SHELL) aiohttp.nix -A interpreter --run "python -c 'import aiohttp'"
+
+aiohttp.nix: aiohttp.txt $(PYPI2NIX)
+	echo "generating aiohttp.nix expressions ..."
+	$(PYPI2NIX) -v \
+		-I $(NIX_PATH) \
 		-V "3.5" \
-		--basename pillow \
-		-r pillow.txt \
-		-E "pkgconfig zlib libjpeg openjpeg libtiff freetype lcms2 libwebp tcl" \
-		-I $(NIX_PATH)
+		--default-overrides \
+		--basename aiohttp \
+		-r aiohttp.txt
 
-pillow.txt: pillow-clear
-	echo "Pillow" > pillow.txt
+aiohttp.txt: aiohttp-clear
+	echo "aiohttp==2.0.6.post1" > aiohttp.txt
 
-pillow-clear:
-	rm -f pillow
-	rm -f pillow.txt
-	rm -f pillow.nix
-	rm -f pillow_frozen.txt
+aiohttp-clear:
+	rm -f aiohttp
+	rm -f aiohttp.txt
+	rm -f aiohttp.nix
+	rm -f aiohttp_frozen.txt
+
+
+#------------------------------------------------------------------------------
+
+
+awscli_and_requests: awscli_and_requests.nix
+	echo "building and testing awscli and requests library ..."
+	$(NIX_BUILD) awscli_and_requests.nix -o awscli_and_requests -A interpreter --show-trace
+	./awscli_and_requests/bin/python -c 'import awscli; import requests'
+	PAGER=none ./awscli_and_requests/bin/aws help
+	$(NIX_SHELL) awscli_and_requests.nix -A interpreter --run "python -c 'import awscli'"
+	$(NIX_SHELL) awscli_and_requests.nix -A interpreter --run "python -c 'import awscli; import requests'"
+	$(NIX_SHELL) awscli_and_requests.nix -A interpreter --run "PAGER=none aws help"
+
+awscli_and_requests.nix: awscli_and_requests.txt $(PYPI2NIX)
+	echo "generating awscli and requests nix expressions ..."
+	$(PYPI2NIX) -v \
+		-I $(NIX_PATH) \
+		-V "2.7" \
+		--default-overrides \
+		-O ./awscli_and_requests_override.nix \
+		--basename awscli_and_requests \
+		-r awscli_and_requests.txt
+
+awscli_and_requests.txt: awscli_and_requests-clear
+	echo "awscli" > awscli_and_requests.txt
+	echo "requests" >> awscli_and_requests.txt
+
+awscli_and_requests-clear:
+	rm -f awscli_and_requests
+	rm -f awscli.txt
+	rm -f requests.txt
+	rm -f awscli_and_requests.nix
+	rm -f awscli_and_requests_frozen.txt
+
+
+#------------------------------------------------------------------------------
+
+
+connexion: connexion.nix
+	echo "building and testing connexion..."
+	$(NIX_BUILD) connexion.nix -o connexion -A interpreter --show-trace -j 1
+	./connexion/bin/python -c 'import connexion'
+	$(NIX_SHELL) connexion.nix -A interpreter --run "python -c 'import connexion'"
+
+connexion.nix: connexion.txt $(PYPI2NIX)
+	echo "generating connexion.nix expressions ..."
+	$(PYPI2NIX) -v \
+		-I $(NIX_PATH) \
+		-V "2.7" \
+		--default-overrides \
+		--basename connexion \
+		-r connexion.txt  \
+		-e vcversioner
+
+connexion.txt: connexion-clear
+	echo "connexion" > connexion.txt
+
+connexion-clear:
+	rm -f connexion
+	rm -f connexion.txt
+	rm -f connexion.nix
+	rm -f connexion_frozen.txt
+
+
+#------------------------------------------------------------------------------
 
 
 empy: empy.nix
@@ -96,12 +170,12 @@ empy: empy.nix
 
 empy.nix: empy.txt $(PYPI2NIX)
 	echo "generating empy nix expressions ..."
-	$(PYPI2NIX) \
-		-v \
-		-V "2.7" \
-		--basename empy \
-		-r empy.txt \
+	$(PYPI2NIX) -v \
 		-I $(NIX_PATH) \
+		-V "2.7" \
+		--default-overrides \
+		--basename empy \
+		-r empy.txt
 
 empy.txt: empy-clear
 	echo "empy" > empy.txt
@@ -111,6 +185,67 @@ empy-clear:
 	rm -f empy.txt
 	rm -f empy.nix
 	rm -f empy_frozen.txt
+
+
+#------------------------------------------------------------------------------
+
+
+flake8: flake8.nix
+	echo "building and testing flake8..."
+	$(NIX_BUILD) flake8.nix -o flake8 -A interpreter --show-trace --fallback
+	./flake8/bin/python -c 'import flake8'
+	$(NIX_SHELL) flake8.nix -A interpreter --run "python -c 'import flake8'"
+
+flake8.nix: flake8.txt $(PYPI2NIX)
+	echo "generating flake8.nix expressions ..."
+	$(PYPI2NIX) -v \
+		-I $(NIX_PATH) \
+		-V "3.5" \
+		--default-overrides \
+		--basename flake8 \
+		-r flake8.txt
+
+flake8.txt: flake8-clear
+	echo "flake8" > flake8.txt
+
+flake8-clear:
+	rm -f flake8
+	rm -f flake8.txt
+	rm -f flake8.nix
+	rm -f flake8_frozen.txt
+
+
+#------------------------------------------------------------------------------
+
+
+ldap: ldap.nix
+	echo "building and testing ldap..."
+	$(NIX_BUILD) ldap.nix -o ldap -A interpreter --show-trace
+	./ldap/bin/python -c 'import ldap'
+	$(NIX_SHELL) ldap.nix -A interpreter --run "python -c 'import ldap'"
+
+ldap.nix: ldap.txt $(PYPI2NIX)
+	echo "generating ldap.nix expressions ..."
+	$(PYPI2NIX) -v \
+		-I $(NIX_PATH) \
+		-V "2.7" \
+		--default-overrides \
+		--basename ldap \
+		-N "NIX_CFLAGS_COMPILE=\"-I\$${pkgs.cyrus_sasl.dev}/include/sasl \$$NIX_CFLAGS_COMPILE\"" \
+		-E "openldap cyrus_sasl openssl" \
+		-r ldap.txt
+
+ldap.txt: ldap-clear
+	echo "python-ldap" > ldap.txt
+
+ldap-clear:
+	rm -f ldap
+	rm -f ldap.txt
+	rm -f ldap.nix
+	rm -f ldap_frozen.txt
+
+
+#------------------------------------------------------------------------------
 
 
 lektor: lektor.nix
@@ -123,13 +258,13 @@ lektor: lektor.nix
 
 lektor.nix: lektor.txt $(PYPI2NIX)
 	echo "generating lektor nix expressions ..."
-	$(PYPI2NIX) \
-		-v \
+	$(PYPI2NIX) -v \
+		-I $(NIX_PATH) \
 		-V "2.7" \
+		--default-overrides \
 		--basename lektor \
-		-r lektor.txt \
 		-E $(LEKTOR_BUILD_INPUTS) \
-		-I $(NIX_PATH)
+		-r lektor.txt
 
 lektor.txt: lektor-clear
 	echo "Lektor" > lektor.txt
@@ -140,6 +275,68 @@ lektor-clear:
 	rm -f lektor.nix
 	rm -f lektor_frozen.txt
 
+
+#------------------------------------------------------------------------------
+
+
+mercurial: mercurial.nix
+	echo "building and testing mercurial..."
+	$(NIX_BUILD) mercurial.nix -o mercurial -A interpreter --show-trace -j 1
+	./mercurial/bin/python -c 'import flake8'
+	$(NIX_SHELL) mercurial.nix -A interpreter --run "python -c 'import flake8'"
+	if ./string_in_file "a209fb6" mercurial.nix ; then true ; else echo "ERROR: Revision 'a209fb6' not found in tornado.nix!"; exit 123; fi
+
+mercurial.nix: mercurial.txt $(PYPI2NIX)
+	echo "generating mercurial.nix expressions ..."
+	$(PYPI2NIX) -v \
+		-I $(NIX_PATH) \
+		-V "2.7" \
+		--default-overrides \
+		--basename mercurial \
+		-E "mercurial" \
+		-r mercurial.txt
+
+
+mercurial.txt: mercurial-clear
+	echo "-e hg+https://bitbucket.org/tarek/flake8@a209fb6#egg=flake8" > mercurial.txt
+
+mercurial-clear:
+	rm -f mercurial
+	rm -f mercurial.txt
+	rm -f mercurial.nix
+	rm -f mercurial_frozen.txt
+
+
+#------------------------------------------------------------------------------
+
+
+pillow: pillow.nix
+	echo "building and testing pillow..."
+	$(NIX_BUILD) pillow.nix -o pillow -A interpreter --show-trace
+	./pillow/bin/python -c 'import PIL'
+	$(NIX_SHELL) pillow.nix -A interpreter --run "python -c 'import PIL'" 
+
+pillow.nix: pillow.txt $(PYPI2NIX)
+	echo "generating pillownix expressions ..."
+	$(PYPI2NIX) -v \
+		-I $(NIX_PATH) \
+		-V "3.5" \
+		--default-overrides \
+		--basename pillow \
+		-E "pkgconfig zlib libjpeg openjpeg libtiff freetype lcms2 libwebp tcl" \
+		-r pillow.txt
+
+pillow.txt: pillow-clear
+	echo "Pillow" > pillow.txt
+
+pillow-clear:
+	rm -f pillow
+	rm -f pillow.txt
+	rm -f pillow.nix
+	rm -f pillow_frozen.txt
+
+
+#------------------------------------------------------------------------------
 
 
 rss2email: rss2email.nix
@@ -152,11 +349,12 @@ rss2email: rss2email.nix
 
 rss2email.nix: rss2email.txt $(PYPI2NIX)
 	echo "generating rss2email nix expressions ..."
-	$(PYPI2NIX) \
-		-v \
+	$(PYPI2NIX) -v \
+		-I $(NIX_PATH) \
+		-V "3.4" \
+		--default-overrides \
 		--basename rss2email \
-		-r rss2email.txt -V "3.4" \
-		-I $(NIX_PATH)
+		-r rss2email.txt 
 
 rss2email.txt: rss2email-clear
 	echo "https://github.com/wking/rss2email/archive/master.zip#egg=rss2email" > rss2email.txt
@@ -168,43 +366,7 @@ rss2email-clear:
 	rm -f rss2email_frozen.txt
 
 
-
-awscli_and_requests: awscli_and_requests.nix
-	echo "building and testing awscli and requests library ..."
-	$(NIX_BUILD) awscli.nix -o awscli_and_requests -A interpreter --show-trace
-	./awscli_and_requests/bin/python -c 'import awscli; import requests'
-	PAGER=none ./awscli_and_requests/bin/aws help
-	$(NIX_SHELL) awscli.nix -A interpreter --run "python -c 'import awscli'"
-	$(NIX_SHELL) awscli.nix -A interpreter --run "python -c 'import awscli; import requests'"
-	$(NIX_SHELL) awscli.nix -A interpreter --run "PAGER=none aws help"
-
-awscli_and_requests.nix: awscli_and_requests.txt $(PYPI2NIX)
-	echo "generating awscli and requests nix expressions ..."
-	$(PYPI2NIX) -v --basename awscli -r awscli.txt -r requests.txt -I $(NIX_PATH) -V "2.7"
-
-awscli_and_requests.txt: awscli_and_requests-clear
-	echo "awscli" > awscli.txt
-	echo "requests" > requests.txt
-
-awscli_and_requests-clear:
-	rm -f awscli_and_requests
-	rm -f awscli.txt
-	rm -f requests.txt
-	rm -f awscli_and_requests.nix
-	rm -f awscli_and_requests_frozen.txt
-
-
-
-vulnix: vulnix-clear $(PYPI2NIX)
-	echo "building and testing vulnix..."
-	git clone https://github.com/garbas/vulnix vulnix-src
-	cd vulnix-src && $(NIX_SHELL) update.nix --argstr pypi2nix "./../$(PYPI2NIX)"
-	NIX_PATH=$(NIX_PATH) $(NIX_BUILD) vulnix-src/default.nix --arg pkgs "import <nixpkgs> {}" -o vulnix
-	./vulnix/bin/vulnix --help
-
-vulnix-clear:
-	rm -f vulnix
-	rm -rf vulnix-src
+#------------------------------------------------------------------------------
 
 
 scipy: scipy.nix
@@ -215,7 +377,15 @@ scipy: scipy.nix
 
 scipy.nix: scipy.txt $(PYPI2NIX)
 	echo "generating scipy.nix expressions ..."
-	$(PYPI2NIX) -v --basename scipy -r scipy.txt -s numpy -E gfortran -E blas -I $(NIX_PATH) -V "3.5"
+	$(PYPI2NIX) -v \
+		-I $(NIX_PATH) \
+		-V "3.5" \
+		--default-overrides \
+		--basename scipy \
+		-s numpy \
+		-E gfortran \
+		-E blas \
+		-r scipy.txt
 
 scipy.txt: scipy-clear
 	echo "scipy" > scipy.txt
@@ -227,6 +397,10 @@ scipy-clear:
 	rm -f scipy.nix
 	rm -f scipy_frozen.txt
 
+
+#------------------------------------------------------------------------------
+
+
 tornado: tornado.nix
 	echo "building and testing tornado..."
 	$(NIX_BUILD) tornado.nix -o tornado -A interpreter --show-trace --fallback
@@ -236,7 +410,12 @@ tornado: tornado.nix
 
 tornado.nix: tornado.txt $(PYPI2NIX)
 	echo "generating tornado.nix expressions ..."
-	$(PYPI2NIX) -v --basename tornado -r tornado.txt -I $(NIX_PATH) -V "3.5" -O 'https://raw.githubusercontent.com/garbas/nixpkgs-python/master/overrides.nix' -O 'git+https://github.com/garbas/nixpkgs-python.git#path=overrides.nix&rev=28ecf4bc8cf5e718862159eb1f324ddcf227dfef' -O './tornado-override/empty.nix'
+	$(PYPI2NIX) -v \
+		-I $(NIX_PATH) \
+		-V "3.5" \
+		--default-overrides \
+		--basename tornado \
+		-r tornado.txt
 
 tornado.txt: tornado-clear
 	echo "-e git+git://github.com/tornadoweb/tornado.git@69253c820df473407c562a227d0ba36df25018ab#egg=tornado" > tornado.txt
@@ -248,114 +427,31 @@ tornado-clear:
 	rm -f tornado_frozen.txt
 
 
-ldap: ldap.nix
-	echo "building and testing ldap..."
-	$(NIX_BUILD) ldap.nix -o ldap -A interpreter --show-trace
-	./ldap/bin/python -c 'import ldap'
-	$(NIX_SHELL) ldap.nix -A interpreter --run "python -c 'import ldap'"
+#------------------------------------------------------------------------------
 
-ldap.nix: ldap.txt $(PYPI2NIX)
-	echo "generating ldap.nix expressions ..."
-	$(PYPI2NIX) \
-		-v \
-		--basename ldap \
-		-N "NIX_CFLAGS_COMPILE=\"-I\$${pkgs.cyrus_sasl.dev}/include/sasl \$$NIX_CFLAGS_COMPILE\"" \
-		-E "openldap cyrus_sasl openssl" \
-		-r ldap.txt \
+
+vulnix: vulnix.nix
+	echo "building and testing vulnix..."
+	$(NIX_BUILD) vulnix.nix -o vulnix -A interpreter --show-trace
+	./vulnix/bin/python -c 'import vulnix'
+	./vulnix/bin/vulnix --help
+	$(NIX_SHELL) vulnix.nix -A interpreter --run "python -c 'import vulnix'"
+	$(NIX_SHELL) vulnix.nix -A interpreter --run "vulnix --help"
+
+vulnix.nix: vulnix.txt $(PYPI2NIX)
+	$(PYPI2NIX) -v \
 		-I $(NIX_PATH) \
-		-V "2.7"
+		-V "3.5" \
+		--default-overrides \
+		--basename vulnix \
+		 -E libxml2 \
+		 -E libxslt \
+		 -r vulnix.txt
 
-ldap.txt: ldap-clear
-	echo "python-ldap" > ldap.txt
-
-ldap-clear:
-	rm -f ldap
-	rm -f ldap.txt
-	rm -f ldap.nix
-	rm -f ldap_frozen.txt
-
-
-mercurial: mercurial.nix
-	echo "building and testing mercurial..."
-	$(NIX_BUILD) mercurial.nix -o mercurial -A interpreter --show-trace -j 1
-	./mercurial/bin/python -c 'import flake8'
-	$(NIX_SHELL) mercurial.nix -A interpreter --run "python -c 'import flake8'"
-	if ./string_in_file "a209fb6" mercurial.nix ; then true ; else echo "ERROR: Revision 'a209fb6' not found in tornado.nix!"; exit 123; fi
-
-mercurial.nix: mercurial.txt $(PYPI2NIX)
-	echo "generating mercurial.nix expressions ..."
-	$(PYPI2NIX) -v --basename mercurial -r mercurial.txt -I $(NIX_PATH) -V "2.7" -E "mercurial"
+vulnix.txt: vulnix-clear
+	git clone https://github.com/flyingcircusio/vulnix vulnix-src --depth 1
+	cp vulnix-src/requirements.txt vulnix.txt
 
 
-mercurial.txt: mercurial-clear
-	echo "-e hg+https://bitbucket.org/tarek/flake8@a209fb6#egg=flake8" > mercurial.txt
-	echo "pytest-runner" >> mercurial.txt
-	echo "setuptools-scm" >> mercurial.txt
-
-mercurial-clear:
-	rm -f mercurial
-	rm -f mercurial.txt
-	rm -f mercurial.nix
-	rm -f mercurial_frozen.txt
-
-connexion: connexion.nix
-	echo "building and testing connexion..."
-	$(NIX_BUILD) connexion.nix -o connexion -A interpreter --show-trace -j 1
-	./connexion/bin/python -c 'import connexion'
-	$(NIX_SHELL) connexion.nix -A interpreter --run "python -c 'import connexion'"
-
-connexion.nix: connexion.txt $(PYPI2NIX)
-	echo "generating connexion.nix expressions ..."
-	$(PYPI2NIX) -v --basename connexion -r connexion.txt -I $(NIX_PATH) -V "2.7" -e vcversioner -O "git+https://github.com/garbas/nixpkgs-python.git#path=overrides.nix"
-
-
-connexion.txt: connexion-clear
-	echo "connexion" > connexion.txt
-
-connexion-clear:
-	rm -f connexion
-	rm -f connexion.txt
-	rm -f connexion.nix
-	rm -f connexion_frozen.txt
-
-
-aiohttp: aiohttp.nix
-	echo "building and testing aiohttp..."
-	$(NIX_BUILD) aiohttp.nix -o aiohttp -A interpreter --show-trace -j 1
-	./aiohttp/bin/python -c 'import aiohttp'
-	$(NIX_SHELL) aiohttp.nix -A interpreter --run "python -c 'import aiohttp'"
-
-aiohttp.nix: aiohttp.txt $(PYPI2NIX)
-	echo "generating aiohttp.nix expressions ..."
-	$(PYPI2NIX) -v --basename aiohttp -r aiohttp.txt -I $(NIX_PATH) -V "3.5"
-
-
-aiohttp.txt: aiohttp-clear
-	echo "aiohttp==2.0.6.post1" > aiohttp.txt
-	echo "pytest-runner" >> aiohttp.txt
-	echo "setuptools-scm" >> aiohttp.txt
-
-aiohttp-clear:
-	rm -f aiohttp
-	rm -f aiohttp.txt
-	rm -f aiohttp.nix
-	rm -f aiohttp_frozen.txt
-
-flake8: flake8.nix
-	echo "building and testing flake8..."
-	$(NIX_BUILD) flake8.nix -o flake8 -A interpreter --show-trace --fallback
-	./flake8/bin/python -c 'import flake8'
-	$(NIX_SHELL) flake8.nix -A interpreter --run "python -c 'import flake8'"
-
-flake8.nix: flake8.txt $(PYPI2NIX)
-	echo "generating flake8.nix expressions ..."
-	$(PYPI2NIX) -v --basename flake8 -r flake8.txt -I $(NIX_PATH) -V "3.5" --default-overrides
-
-flake8.txt: flake8-clear
-	echo "flake8" > flake8.txt
-
-flake8-clear:
-	rm -f flake8
-	rm -f flake8.txt
-	rm -f flake8.nix
-	rm -f flake8_frozen.txt
+vulnix-clear:
+	rm -rf vulnix*
